services:
  # TODO: optimize client create time
  client:
    build:
      context: ./client/
      dockerfile: dev.Dockerfile
    environment:
      - NEXT_PUBLIC_BACKEND_URL=/api/
    volumes:
      - ./client/:/usr/src/app
      - /usr/src/app/node_modules
    container_name: gdg-client-dev

  server:
    build:
      context: ./server/
      dockerfile: dev.Dockerfile
    env_file:
      - ./server/.env
    volumes:
      - ./server/:/app
    container_name: gdg-server-dev
    

  nginx:
    image: nginx:1.29-alpine
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse_proxy
    # TODO: depend on server's health check
    depends_on:
      - client
      - server

    
